config/routes.rb
Rails.application.routes.draw do
  
  root "projects#index"
  # get "projects" => 'projects#index'
  # get "projects/new" => 'projects#new'
  # get "projects/:id" => 'projects#show', as: "project"
  # get "projects/:id/edit" => 'projects#edit', as: 'edit_project'
  # patch "projects/:id" => 'projects#update'
  resources :projects do
  	resources :pledges
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  validates :name, presence: true
  validates :email, format: {with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
  ALLOWED_AMOUNTS = [25, 50, 100, 200, 500]
  validates :pledge_amount, inclusion: {in: ALLOWED_AMOUNTS}
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :description, length: {maximum: 500}
	validates :target_pledge_amount, numericality: {greater_than: 0}
	validates :image_file_name, allow_blank: true, format: {
  	with:    /\w+\.(gif|jpg|png)\z/i,
  	message: "must reference a GIF, JPG, or PNG image"
	}

	has_many :pledges, dependent: :destroy

	def pledging_expired?
		Time.now > pledging_ends_on
	end

	def self.accepting
		where("pledging_ends_on > ?", Time.now)
	end

	def total_pledged
		total = 0
		pledges.each do |p|
			total += p['pledge_amount']
		end
		total
	end

	def pledge_outstanding
		target_pledge_amount - total_pledged
	end

	def fully_funded?
		pledge_outstanding <= 0
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	def index
		@project = Project.find(params[:project_id])
		@pledges = @project.pledges
	end
	def new
		@project = Project.find(params[:project_id])
		@pledge = @project.pledges.new
	end
	def create
		@project = Project.find(params[:project_id])
		@pledge = @project.pledges.new(pledge_params)
		if @pledge.save
			redirect_to project_pledges_path(@project), notice: 'Thanks for your support'
		else
			render :new
		end
	end
	private 
		def pledge_params
			params.require(:pledge).permit(:name, :email, :pledge_amount, :comment)
		end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.accepting
	end

	def show 
		@project = Project.find(params[:id])
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		if @project.update(project_params)
			redirect_to @project, notice: 'project updated'
		else
			render :edit
		end
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to root_path, notice: 'project updated'
		else
			render :new
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to root_path, notice: "all gone :("
	end

	private
		def project_params
			params.require(:project).permit(:name, :description, :image_file_name, :team_members,
																			:target_pledge_amount, :pledging_ends_on, :website)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def format_pledging_time(project)
		if project.pledging_expired?
			content_tag(:bold, "All Done!")
		else
			"#{distance_of_time_in_words(Time.now, project.pledging_ends_on)} from now"
		end
	end

	def image_for(project)
		if project.image_file_name.blank?
			image_tag('cat.jpg')
		else
			image_tag(project.image_file_name)
		end
	end

	def format_pledging_link(project)
		if project.fully_funded?
			content_tag(:strong, "Funded!")
		else
			link_to "pay us", new_project_pledge_path(project) 
		end
	end
end

app/views/layouts/_footer.html.erb
<footer id='page-footer'>
	<p>Copyright &copy; 2017</p>
	<p>Rails Rocks Man!</p>
</footer>

app/views/layouts/_header.html.erb
<header id='page-header'>
  <h1>Crowdfund</h1>
</header>

app/views/layouts/_sidebar.html.erb
<aside id='sidebar'>
	<nav>
		<ul>
			<li><%= link_to 'New Project', new_project_path %></li>
			<li><%= link_to "All Projects", projects_path %></li>
		</ul>
	</nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfund</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
  	<%= render 'layouts/sidebar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pledges/index.html.erb
<h1>pledges for <%= link_to @project.name, @project %></h1>
<ul>
	<% @pledges.each do |pledge| %>
		<li><h2><%= pledge.name %> (<%= number_to_currency(pledge.pledge_amount) %>)</h2></li>
	<% end %>
</ul>

app/views/pledges/new.html.erb
<%= form_for [@project, @pledge] do |f| %>
	<%= render 'shared/errors', object: @pledge %>
	<p>
		<%= f.label :name %></br>
		<%= f.text_field :name, autofocus: true %></br>
	</p>
	<p>
		<%= f.label :email %></br>
		<%= f.text_field :email %></br>
	</p>
	<p>
		<%= f.label :amount %>
		<%= f.select :pledge_amount, Pledge::ALLOWED_AMOUNTS, prompt: "please select" %></br>
	</p>
	<p>
		<%= f.label :any_comments %></br>
		<%= f.text_field :comment %></br>
	</p>
	<p>
		<%= f.submit %> |
		<%= link_to 'cancel', project_pledges_path(@project) %>
	</p>
<% end %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<%= render 'shared/errors', object: @project %>
	<p>
		<%= f.label :name %></br>
		<%= f.text_field :name, autofocus: true %></br>
	</p>
	<p>
		<%= f.label :description %></br>
		<%= f.text_area :description, cols: 40, rows: 7 %></br>
	</p>
	<p>
		<%= f.label :target_pledge_amount %></br>
		<%= f.number_field :target_pledge_amount %></br>
	</p>
	<p>
		<%= f.label :pledging_ends_on %></br>
		<%= f.date_field :pledging_ends_on %></br>
	</p>
	<p>
		<%= f.label :image_file_name %></br>
		<%= f.text_field :image_file_name %></br>
	</p>
	<p>
		<%= f.label :team_members %></br>
		<%= f.text_field :team_members %></br>
	</p>
	<p>
		<%= f.label :website %></br>
		<%= f.text_field :website %></br>
	</p>
	<p>
		<%= f.submit %> |
		<%= link_to 'cancel', projects_path %>
	</p>
<% end %>

app/views/projects/edit.html.erb
<H1>Editing <%= @project.name %></H1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1><%= pluralize(@projects.length, "Project") %></h1>
<div>
	<ul>
		<% @projects.each do |project| %>
			<li><h2><strong><%= link_to project.name, project %></strong></h2></li>
			<%= image_for project %>
			<p><%= truncate(project.description, length: 20, separator: ' ') %></p>
			<h4>target pledge: <%= number_to_currency(project.target_pledge_amount) %></h4>
			<h4>Pledging ends on: <%= format_pledging_time(project) %></h4>
		<% end %>
  </ul>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h2><strong><%= @project.name %></strong></h2></li>
<%= image_for @project %>
<p><%= @project.description %></p>
<h4>Pledging ends on: <%= format_pledging_time(@project) %></h4>
<h4>Team: <%= @project.team_members %></h4>
<% if !@project.fully_funded? %>
	<h4>target pledge: <%= number_to_currency(@project.target_pledge_amount) %></h4>
	<h4><%= number_to_currency(@project.total_pledged) %> pledged</h4>
	<h4><%= number_to_currency(@project.pledge_outstanding) %> outstanding</h4>
<% end %>


<%= link_to "Edit", edit_project_path %> | 
<%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: 'Are you sure?'} %> | 
<%= link_to "who pledged?", project_pledges_path(@project) %> | 
<%= format_pledging_link(@project) %>
<h2>Thanks!</h2>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<ul>
		<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
<% end %>